### ISSUE TITLE
favicon and logo icons cause 404

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-homepage#70]
```
[ambassador-6f569f88c4-7lrmw] ACCESS [2019-02-15T20:51:29.958Z] "GET /auth/resources/4.2.1.final/login/hmda/img/favicons/favicon.ico HTTP/1.1" 200 - 0 67646 1 1 "OUTSIDE IP" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko" "82a40404-a0bb-49f4-acb1-1569e9297945" "ffiec.cfpb.gov" "CLUSTERIP:80"
```

```
[ambassador-6f569f88c4-9q89x] ACCESS [2019-02-15T20:49:01.229Z] "GET /img/ffiec-logo.svg HTTP/1.1" 404 - 0 162 0 0 "OUTSIDE IP" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko" "b4bab169-bcbf-43e1-b504-7ff5acd7272e" "ffiec.cfpb.gov" "CLUSTERIP:80"
```

**Comment by zencircle** [comment]
https://stackoverflow.com/questions/12480497/why-am-i-getting-error-for-apple-touch-icon-precomposed-png

**Comment by awolfe76** [comment]
The first message there looks like a `200`, so I think that one is ok.

The second message is because we don't actually publish that image anymore. This can be fixed by adding a `public/img/ffiec-logo.svg` file. Then that file will only be directly copied over during the build process (it will not have a hash, ie `ffiec-logo.69ef8d9f.svg`).

**Comment by meissadia** [comment]
`ffiec-logo.svg` is included and referenced within the unified front-end repo.  Closing this.
