### ISSUE TITLE
When deployed to beta, remove certain blocks

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-homepage#93]
When hmda-homepage is deployed to beta, we would like to delete some blocks since they are not available on beta but rather only on main (default).

**Comment by omnipresent07** [comment]
Proposal for what it _could_ look like. Also, messaging for 2019 platform needs to be updated -- at the moment it doesn't say much about 2019 filing. 
<img width="1680" alt="Screen Shot 2019-09-26 at 8 47 42 AM" src="https://user-images.githubusercontent.com/44377678/65689148-617fc800-e03a-11e9-8dc6-8e43bb08d245.png">

**Comment by kgudel** [comment]
For the documentation in the `hmda-data-browser` we have decided to link to the default production `hmda-documentation` page. Since, it opens a new tab when that link is opened we keep the separation between production and beta. If we decide to add new beta features to the `hmda-data-browser` we can add the features to the production `hmda-documentation` and a note next to that documentation that they are for beta only.
